# Generated by Django 5.2.3 on 2026-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_device_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='embedding',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
