# Generated by Django 5.2.3 on 2026-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_specification_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='specification_template',
            field=models.JSONField(default=list),
        ),
    ]
