# Generated by Django 5.2.3 on 2026-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_specification_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quantity_rented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='quantity_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
