# Generated by Django 5.2.3 on 2026-09-05 15:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_device_quantity_rented_device_quantity_storage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', django.db.models.expressions.CombinedExpression(models.F('quantity_storage'), '+', models.F('quantity_rented')))), name='quantity_equals_storage_plus_rented'),
        ),
    ]
