# Generated by Django 5.2.3 on 2026-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_requests',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_restore_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
