# Generated by Django 5.2.3 on 2026-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('domain', models.CharField(choices=[('catalog', 'Catalog'), ('service', 'Service'), ('general', 'General')], max_length=20)),
                ('embedding', models.JSONField()),
            ],
        ),
    ]
