# Generated by Django 5.2.3 on 2026-08-08 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_cart_cartitem_rentalrequest_rentalrequestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('returned', 'Возвращена')], default='pending', max_length=20),
        ),
    ]
