# Generated by Django 5.2.3 on 2026-08-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rentalrequest_id_alter_rentalrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='pdf',
        ),
    ]
