# Generated by Django 5.2.3 on 2026-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_rentalrequest_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('returned', 'Возвращена'), ('hidden', 'Скрыта')], default='pending', max_length=20),
        ),
    ]
